services:
  - type: web
    name: slot-booker-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn 'backend.app:create_app()'
    envVars:
      - key: FLASK_ENV
        value: production

      - key: DATABASE_URL
        value: postgresql://postgres:WapibbdjCpIgKsrptZhXNBcCxomWbCSo@maglev.proxy.rlwy.net:34649/railway
        fromDatabase:
          name: slot-booker-db
          property: connectionString

      - key: MAIL_USERNAME
        value: your-email@example.com

      - key: MAIL_PASSWORD
        value: your-email-password

      - key: PYTHONPATH
        value: backend

    autoDeploy: true
    buildFilter:
      paths:
        - backend/**

databases:
  - name: slot-booker-db
    databaseName: slotbooker
    user: slotbooker_user
